name: Build and deploy container app

on:
  push:
    branches:
      - action
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Tree view
      run: |
          ls -la
          sudo apt-get install -y tree
          tree .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DH_username }}
        password: ${{ secrets.DH_password }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sathya1082/pyserver-GH${{ github.sha }}
        file: ./doc_workshop/Dockerfile
